server:
   port: 8082
spring:
   application:
      name: xxl-job-client
xxl:
   job:
      accessToken: 
      admin:
         addresses: http://172.17.17.165:8080/xxl-job-admin
         username: admin
         password: 123456
      executor:
         appname: xxl-job-executor-sample
         address: 
         ip: 
         port: 9999
         logpath: logs/applogs/xxl-job/jobhandler
         logretentiondays: 30